### ISSUE TITLE
一个小问题

### ISSUE THREAD

**Issue by trust-youself** [FunnyWolf/TFirewall#2]
./tfs_linux_amd64 socks5 80 1080    tfc_windows_386.exe socks5 10.10.10.10 80  无反应  连接1080 才有socks5连接

**Comment by FunnyWolf** [comment]
> ./tfs_linux_amd64 socks5 80 1080 tfc_windows_386.exe socks5 10.10.10.10 80 无反应 连接1080 才有socks5连接

无反应是正常现象,在不使用socks5连接时是没有日志的,可以尝试将代理配置为 socks5:10.10.10.10:1080,就会发现已经进入tfc的内网了.
